CREATE TABLE IF NOT EXISTS elements (
    id STRING NOT NULL PRIMARY KEY,
    record_id STRING,
    element_id STRING,
    text STRING,
    embeddings ARRAY<FLOAT>,
    type STRING,
    url STRING,
    version STRING,
    data_source_date_created TIMESTAMP,
    data_source_date_modified TIMESTAMP,
    data_source_date_processed TIMESTAMP,
    data_source_permissions_data STRING,
    data_source_filesize_bytes FLOAT,
    data_source_url STRING,
    data_source_version STRING,
    data_source_record_locator STRING,
    category_depth INT,
    parent_id STRING,
    attached_filename STRING,
    filetype STRING,
    last_modified TIMESTAMP,
    file_directory STRING,
    filename STRING,
    languages ARRAY<STRING>,
    page_number STRING,
    links STRING,
    page_name STRING,
    link_urls STRING,
    link_texts STRING,
    sent_from STRING,
    sent_to STRING,
    subject STRING,
    section STRING,
    header_footer_type STRING,
    emphasized_text_contents STRING,
    emphasized_text_tags STRING,
    text_as_html STRING,
    regex_metadata STRING,
    detection_class_prob FLOAT,
    is_continuation BOOLEAN,
    orig_elements STRING,
    coordinates_points STRING,
    coordinates_system STRING,
    coordinates_layout_width FLOAT,
    coordinates_layout_height FLOAT
);

