services:
  chroma:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/8000' || exit 1
      interval: 5s
      timeout: 10s
      retries: 3
