name: "Setup Environment"
description: "Sets up the environment for running the tests"

inputs:
  python-version:
    description: "Python version"
    default: "3.10"


runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Generate Cache Key
      id: cache-key
      uses: ./.github/actions/generate-cache-key
      with:
        python-version: ${{ inputs.python-version }}

    - name: Restore Virtual Environment Cache
      id: cache-restore
      uses: actions/cache@v4
      with:
        key: ${{ steps.cache-key.outputs.cache-key }}
        path: ${{ inputs.work-dir }}/.venv

    - name: Set up Python environment
      uses: ./.github/actions/setup-python
      with:
        python-version: ${{ inputs.python-version }}


    # Don't install all the local partitioning deps
    - name: Install dependencies
      shell: bash
      run: |
        uv sync --frozen --all-extras --all-groups  \
        --no-extra doc \
        --no-extra docx \
        --no-extra epub \
        --no-extra image \
        --no-extra md \
        --no-extra msg \
        --no-extra odt \
        --no-extra org \
        --no-extra pdf \
        --no-extra ppt \
        --no-extra pptx \
        --no-extra rst \
        --no-extra rtf \
        --no-extra tsv \
        --no-extra xlsx

    - name: Cache Virtual Environment (Final)
      uses: actions/cache@v4
      with:
        key: ${{ steps.cache-key.outputs.cache-key }}
        path: ${{ inputs.work-dir }}/.venv
