CREATE TABLE elements (
    id VARCHAR(36) PRIMARY KEY NOT NULL DEFAULT UUID_STRING(),
    record_id VARCHAR,
    element_id VARCHAR,
    text VARCHAR,
    embeddings VECTOR(FLOAT, 1536),
    type VARCHAR,
    system VARCHAR,
    layout_width DECIMAL,
    layout_height DECIMAL,
    points VARCHAR,
    url VARCHAR,
    version VARCHAR,
    date_created TIMESTAMP_TZ,
    date_modified TIMESTAMP_TZ,
    date_processed TIMESTAMP_TZ,
    permissions_data VARCHAR,
    record_locator VARCHAR,
    category_depth INTEGER,
    parent_id VARCHAR,
    attached_filename VARCHAR,
    filetype VARCHAR,
    last_modified TIMESTAMP_TZ,
    file_directory VARCHAR,
    filename VARCHAR,
    languages ARRAY,
    page_number VARCHAR,
    links VARCHAR,
    page_name VARCHAR,
    link_urls ARRAY,
    link_texts ARRAY,
    sent_from ARRAY,
    sent_to ARRAY,
    subject VARCHAR,
    section VARCHAR,
    header_footer_type VARCHAR,
    emphasized_text_contents ARRAY,
    emphasized_text_tags ARRAY,
    text_as_html VARCHAR,
    regex_metadata VARCHAR,
    detection_class_prob DECIMAL,
    image_base64 VARCHAR,
    image_mime_type VARCHAR,
    orig_elements VARCHAR,
    is_continuation BOOLEAN
);
