CREATE TABLE elements (
    id UUID PRIMARY KEY,
    element_id VARCHAR,
    text TEXT,
    embeddings ARRAY(FLOAT),
    type VARCHAR,
    system VARCHAR,
    layout_width DECIMAL,
    layout_height DECIMAL,
    points TEXT,
    url TEXT,
    version VARCHAR,
    date_created TIMESTAMP_TZ,
    date_modified TIMESTAMP_TZ,
    date_processed TIMESTAMP_TZ,
    permissions_data TEXT,
    record_locator TEXT,
    category_depth INTEGER,
    parent_id VARCHAR,
    attached_filename VARCHAR,
    filetype VARCHAR,
    last_modified TIMESTAMP_TZ,
    file_directory VARCHAR,
    filename VARCHAR,
    languages ARRAY(VARCHAR),
    page_number VARCHAR,
    links TEXT,
    page_name VARCHAR,
    link_urls ARRAY(VARCHAR),
    link_texts ARRAY(VARCHAR),
    sent_from ARRAY(VARCHAR),
    sent_to ARRAY(VARCHAR),
    subject VARCHAR,
    section VARCHAR,
    header_footer_type VARCHAR,
    emphasized_text_contents ARRAY(VARCHAR),
    emphasized_text_tags ARRAY(VARCHAR),
    text_as_html TEXT,
    regex_metadata TEXT,
    detection_class_prob DECIMAL
);

