name: "Setup Python Environment"
description: "Installs Python and sets up a virtual environment"
inputs:

  python-version:
    description: "Python version"
    required: false
    default: "3.12.6"
runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        python-version: ${{ matrix.python-version }}

    - name: Set up Python
      shell: bash
      run: uv python install

    - name: Create Virtual Environment (if missing)
      shell: bash
      working-directory: ${{ inputs.work-dir }}
      run: |
        if [ ! -d ".venv" ]; then
          uv venv
          echo "./.venv/bin" >> $GITHUB_PATH
          echo "VIRTUAL_ENV=./.venv" >> $GITHUB_ENV
        fi
