name: Setup Environment

on:
  workflow_call:
    inputs:
      runs-on:
        description: "Runner type"
        type: string
        default: "ubuntu-latest"
      python-version:
        description: "Python version"
        type: string
        default: "3.10"

jobs:
  setup-environment:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Cache Key
        id: cache-key
        uses: ./.github/actions/generate-cache-key
        with:
          python-version: ${{ inputs.python-version }}

      - name: Restore Virtual Environment Cache
        id: cache-restore
        uses: actions/cache@v4
        with:
          key: ${{ steps.cache-key.outputs.cache-key }}
          path: ${{ inputs.work-dir }}/.venv

      - name: Set up Python environment
        uses: ./.github/actions/setup-python
        with:
          python-version: ${{ inputs.python-version }}


      - name: Install dependencies
        run: uv sync --frozen --all-extras --all-groups

      - name: Cache Virtual Environment (Final)
        uses: actions/cache@v4
        with:
          key: ${{ steps.cache-key.outputs.cache-key }}
          path: ${{ inputs.work-dir }}/.venv
